"""Contains constants used for configuring the tasks defined in the `eventHandlers` module."""

WHEEL_SCROLL_DISTANCE = 80
SCROLL_DISTANCE_MULTIPLIER = 3

ZOOMING_DISTANCE = 20
ZOOMING_DISTANCE_MULTIPLIER = 1

MOUSE_MOVEMENT_DISTANCE_SMALL  = 5
MOUSE_MOVEMENT_DISTANCE_BASE   = 20
MOUSE_MOVEMENT_DISTANCE_MEDIUM = 40
MOUSE_MOVEMENT_DISTANCE_LARGE  = 80

WINDOW_MOVEMENT_DISTANCE_SMALL  = 2
WINDOW_MOVEMENT_DISTANCE_MEDIUM = 10
WINDOW_MOVEMENT_DISTANCE_LARGE  = WINDOW_MOVEMENT_DISTANCE_MEDIUM * 2
